### ISSUE TITLE
Script error on MacOS

### ISSUE THREAD

**Issue by warthog3** [hansonw/itunesfm#6]
Is my play count too high for this script?

```
Fetching play counts.. (29000/29382)
{ Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:323:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:235:13)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
  cmd: 'osascript -l JavaScript -e \'var old = console.log; console.log = function () { Array.prototype.unshift.call(arguments, "<brandonhorst:node-osa>"); Array.prototype.push.call(arguments, "</brandonhorst:node-osa>"); old.apply(console, arguments); }; JSON.stringify((function () {\' -e \'                var itunes = Application(\'\\\'\'iTunes\'\\\'\');\' -e \'                var tracks = itunes.libraryPlaylists[0].tracks;\' -e \'                var result = {};\' -e \'                for (var i = 0; i < tracks.length; i++) {\' -e \'                  var track = tracks[i];\' -e \'                  if (track.videoKind() !== \'\\\'\'none\'\\\'\') {\' -e \'                    continue;\' -e \'                  }\' -e \'                  result[track.persistentID()] = {\' -e \'                    name: track.name(),\' -e \'                    artist: track.artist(),\' -e \'                    playedCount: track.playedCount()\' -e \'                  };\' -e \'                }\' -e \'                return result;\' -e \'              })());\'' }
```

**Comment by MBybee** [comment]
Similar error, and I assume this project is dead, but hopefully someone will pick it up:

```
Fetching play counts.. (11000/11917)
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (node:child_process:482:14)
    at Socket.emit (node:events:507:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23) {
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',
  cmd: `osascript -l JavaScript -e 'var old = console.log; console.log = function () { Array.prototype.unshift.call(arguments, "<brandonhorst:node-osa>"); Array.prototype.push.call(arguments, "</brandonhorst:node-osa>"); old.apply(console, arguments); }; JSON.stringify((() => {' -e '            var itunes = Application('\\''Music'\\'');' -e '            var tracks = itunes.libraryPlaylists[0].tracks;' -e '            var result = {};' -e '            for (var i = 0; i < tracks.length; i++) {' -e '                var track = tracks[i];' -e '                result[track.persistentID()] = {' -e '                    name: track.name(),' -e '                    artist: track.artist(),' -e '                    playedCount: track.playedCount()' -e '                };' -e '            }' -e '            return result;' -e '        })());'`
}
```

At just about 12,000 scrobbles, which isn't really that many.

**Comment by hansonw** [comment]
finally got around to fixing this! `npx itunesfm` should pick up the latest version.
